Import('env build_config')


sources = ["HypergraphImpl.cpp", "HypergraphAlgorithms.cpp", "EdgeCache.cpp", "CubePruning.cpp", "ExtendCKY.cpp", 
           "Hypothesis.cpp", "AStar.cpp", "BestHyp.cpp", "Hypergraph.cpp", "Weights.cpp", "hypergraph.pb.cc", "features.pb.cc"]

hyp_lib = env.Library('hypergraph', sources)

env.Program('test', ["Test.cpp", hyp_lib])

Return('hyp_lib')
