Import('env build_config')


sources = ["HypergraphImpl.cpp", "HypergraphAlgorithms.cpp", "EdgeCache.cpp", 
           "CubePruning.cpp", "ExtendCKY.cpp", 
           "Hypothesis.cpp", "AStar.cpp", "BestHyp.cpp", "Hypergraph.cpp", "Weights.cpp", 
           "$HYP_PROTO/hypergraph.pb.cc",
           "$HYP_PROTO/tag.pb.cc", 
           "$HYP_PROTO/features.pb.cc"]

hyp_lib = env.Library('hypergraph', sources)

env.Program('test', ["Test.cpp", hyp_lib])

env.Program('convert', ["ConvertFromFile.cpp", hyp_lib])

Return('hyp_lib')
