env = Environment(CC = 'g++',
                  CPPFLAGS = '-g')


sources = ["Forest.cpp", "ForestAlgorithms.cpp", "hypergraph.pb.cc", "features.pb.cc", "translation.pb.cc", "lexical.pb.cc", "EdgeCache.cpp", "CubePruning.cpp", "Test.cpp"]
libs = ["pthread", "cpptest", "protobuf"]


env.Library('hypergraph', sources , LIBS = libs, CPPPATH = ['.', '/home/srush/Projects/transforest/svector/',  '/home/srush/Projects/hypergraph/gen_cpp/'])

env.Program('test', sources , LIBS = libs, CPPPATH = ['.', '/home/srush/Projects/transforest/svector/',  '/home/srush/Projects/hypergraph/gen_cpp/'])