

sources = ["Forest.cpp", "ForestAlgorithms.cpp", "hypergraph.pb.cc", "features.pb.cc", "translation.pb.cc", "lexical.pb.cc", "EdgeCache.cpp", "Test.cpp"]
libs = ["pthread", "cpptest", "protobuf"]
Library('hypergraph', sources , LIBS = libs, CPPPATH = ['.', '/home/srush/Projects/transforest/svector/',  '/home/srush/Projects/hypergraph/gen_cpp/'])