# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2

NODE_FV_FIELD_NUMBER = 100
node_fv = descriptor.FieldDescriptor(
  name='node_fv', full_name='node_fv', index=0,
  number=100, type=9, cpp_type=9, label=1,
  default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
EDGE_FV_FIELD_NUMBER = 100
edge_fv = descriptor.FieldDescriptor(
  name='edge_fv', full_name='edge_fv', index=1,
  number=100, type=9, cpp_type=9, label=1,
  default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

import hypergraph_pb2


hypergraph_pb2.Hypergraph.Node.RegisterExtension(node_fv)
hypergraph_pb2.Hypergraph.Edge.RegisterExtension(edge_fv)
