# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2

IS_WORD_FIELD_NUMBER = 110
is_word = descriptor.FieldDescriptor(
  name='is_word', full_name='is_word', index=0,
  number=110, type=8, cpp_type=7, label=1,
  default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
WORD_FIELD_NUMBER = 111
word = descriptor.FieldDescriptor(
  name='word', full_name='word', index=1,
  number=111, type=9, cpp_type=9, label=1,
  default_value=unicode("", "utf-8"),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

import hypergraph_pb2


hypergraph_pb2.Hypergraph.Node.RegisterExtension(is_word)
hypergraph_pb2.Hypergraph.Node.RegisterExtension(word)
