# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='lattice.proto',
  package='lattice',
  serialized_pb='\n\rlattice.proto\x12\x07lattice\"\xe1\x01\n\x07Lattice\x12\r\n\x05start\x18\x05 \x02(\x05\x12\r\n\x05\x66inal\x18\x06 \x03(\x05\x12#\n\x04node\x18\x07 \x03(\x0b\x32\x15.lattice.Lattice.Node\x1aM\n\x04Node\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12#\n\x04\x65\x64ge\x18\x03 \x03(\x0b\x32\x15.lattice.Lattice.Edge*\x05\x08\x64\x10\xc8\x01\x1a\x37\n\x04\x45\x64ge\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05to_id\x18\x03 \x02(\x05*\x05\x08\x64\x10\xc8\x01*\x04\x08\x01\x10\x05*\x05\x08\x64\x10\xc8\x01\"X\n\x07Subword\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x1b\n\x13subword_original_id\x18\x02 \x01(\x05\x12\"\n\x1asubword_hypergraph_node_id\x18\x03 \x01(\x05\"N\n\tPhraselet\x12\x1e\n\x04word\x18\x01 \x03(\x0b\x32\x10.lattice.Subword\x12!\n\x19phraselet_hypergraph_edge\x18\x02 \x01(\x05\"3\n\nPhraselets\x12%\n\tphraselet\x18\x01 \x03(\x0b\x32\x12.lattice.Phraselet\"J\n\x06Origin\x12\x17\n\x0fhypergraph_edge\x18\x01 \x03(\x05\x12\x13\n\x0boriginal_id\x18\x02 \x01(\x05\x12\x12\n\nhas_origin\x18\x03 \x01(\x08:>\n\nphraselets\x12\x15.lattice.Lattice.Node\x18\x64 \x01(\x0b\x32\x13.lattice.Phraselets:*\n\x0bhas_phrases\x12\x15.lattice.Lattice.Node\x18\x65 \x01(\x08:6\n\x06origin\x12\x15.lattice.Lattice.Edge\x18n \x01(\x0b\x32\x0f.lattice.Origin:.\n\x14num_hypergraph_edges\x12\x10.lattice.Lattice\x18y \x01(\x05:*\n\x10num_original_ids\x12\x10.lattice.Lattice\x18z \x01(\x05')


PHRASELETS_FIELD_NUMBER = 100
phraselets = descriptor.FieldDescriptor(
  name='phraselets', full_name='lattice.phraselets', index=0,
  number=100, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
HAS_PHRASES_FIELD_NUMBER = 101
has_phrases = descriptor.FieldDescriptor(
  name='has_phrases', full_name='lattice.has_phrases', index=1,
  number=101, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
ORIGIN_FIELD_NUMBER = 110
origin = descriptor.FieldDescriptor(
  name='origin', full_name='lattice.origin', index=2,
  number=110, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
NUM_HYPERGRAPH_EDGES_FIELD_NUMBER = 121
num_hypergraph_edges = descriptor.FieldDescriptor(
  name='num_hypergraph_edges', full_name='lattice.num_hypergraph_edges', index=3,
  number=121, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
NUM_ORIGINAL_IDS_FIELD_NUMBER = 122
num_original_ids = descriptor.FieldDescriptor(
  name='num_original_ids', full_name='lattice.num_original_ids', index=4,
  number=122, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_LATTICE_NODE = descriptor.Descriptor(
  name='Node',
  full_name='lattice.Lattice.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='lattice.Lattice.Node.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='label', full_name='lattice.Lattice.Node.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='edge', full_name='lattice.Lattice.Node.edge', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 200), ],
  serialized_start=105,
  serialized_end=182,
)

_LATTICE_EDGE = descriptor.Descriptor(
  name='Edge',
  full_name='lattice.Lattice.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='lattice.Lattice.Edge.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='label', full_name='lattice.Lattice.Edge.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to_id', full_name='lattice.Lattice.Edge.to_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 200), ],
  serialized_start=184,
  serialized_end=239,
)

_LATTICE = descriptor.Descriptor(
  name='Lattice',
  full_name='lattice.Lattice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='start', full_name='lattice.Lattice.start', index=0,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='final', full_name='lattice.Lattice.final', index=1,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='node', full_name='lattice.Lattice.node', index=2,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LATTICE_NODE, _LATTICE_EDGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1, 5), (100, 200), ],
  serialized_start=27,
  serialized_end=252,
)


_SUBWORD = descriptor.Descriptor(
  name='Subword',
  full_name='lattice.Subword',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='word', full_name='lattice.Subword.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='subword_original_id', full_name='lattice.Subword.subword_original_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='subword_hypergraph_node_id', full_name='lattice.Subword.subword_hypergraph_node_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=254,
  serialized_end=342,
)


_PHRASELET = descriptor.Descriptor(
  name='Phraselet',
  full_name='lattice.Phraselet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='word', full_name='lattice.Phraselet.word', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='phraselet_hypergraph_edge', full_name='lattice.Phraselet.phraselet_hypergraph_edge', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=344,
  serialized_end=422,
)


_PHRASELETS = descriptor.Descriptor(
  name='Phraselets',
  full_name='lattice.Phraselets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='phraselet', full_name='lattice.Phraselets.phraselet', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=424,
  serialized_end=475,
)


_ORIGIN = descriptor.Descriptor(
  name='Origin',
  full_name='lattice.Origin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hypergraph_edge', full_name='lattice.Origin.hypergraph_edge', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='original_id', full_name='lattice.Origin.original_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='has_origin', full_name='lattice.Origin.has_origin', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=477,
  serialized_end=551,
)


_LATTICE_NODE.fields_by_name['edge'].message_type = _LATTICE_EDGE
_LATTICE_NODE.containing_type = _LATTICE;
_LATTICE_EDGE.containing_type = _LATTICE;
_LATTICE.fields_by_name['node'].message_type = _LATTICE_NODE
_PHRASELET.fields_by_name['word'].message_type = _SUBWORD
_PHRASELETS.fields_by_name['phraselet'].message_type = _PHRASELET

class Lattice(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Node(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LATTICE_NODE
    
    # @@protoc_insertion_point(class_scope:lattice.Lattice.Node)
  
  class Edge(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LATTICE_EDGE
    
    # @@protoc_insertion_point(class_scope:lattice.Lattice.Edge)
  DESCRIPTOR = _LATTICE
  
  # @@protoc_insertion_point(class_scope:lattice.Lattice)

class Subword(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUBWORD
  
  # @@protoc_insertion_point(class_scope:lattice.Subword)

class Phraselet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHRASELET
  
  # @@protoc_insertion_point(class_scope:lattice.Phraselet)

class Phraselets(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHRASELETS
  
  # @@protoc_insertion_point(class_scope:lattice.Phraselets)

class Origin(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ORIGIN
  
  # @@protoc_insertion_point(class_scope:lattice.Origin)

phraselets.message_type = _PHRASELETS
Lattice.Node.RegisterExtension(phraselets)
Lattice.Node.RegisterExtension(has_phrases)
origin.message_type = _ORIGIN
Lattice.Edge.RegisterExtension(origin)
Lattice.RegisterExtension(num_hypergraph_edges)
Lattice.RegisterExtension(num_original_ids)
# @@protoc_insertion_point(module_scope)
