Import('env')


sources = ["Subgradient.cpp", "DualDecomposition.cpp", "MRF.cpp", "MRFHypergraph.cpp", "mrf.pb.cc"]

lib = env.Library('optimization', sources)

#env.Program('test', ["Test.cpp", hyp_lib])

Return('lib')
