Import('env build_config')

sources = ["Forest.cpp", 
           "$HYP_PROTO/hypergraph.pb.cc", "$HYP_PROTO/features.pb.cc", "$HYP_PROTO/translation.pb.cc", 
           "$HYP_PROTO/lexical.pb.cc"]

trans_lib = env.Library('transforest', sources )

Return('trans_lib')

