Import('env build_config')

sources = ["Forest.cpp", "hypergraph.pb.cc", "features.pb.cc", "translation.pb.cc", "lexical.pb.cc"]

trans_lib = env.Library('transforest', sources )

Return('trans_lib')

