Import('env')

proto = ["lattice.proto"]

py_dir = Dir('.').abspath+'/gen-py/'
cpp_dir = Dir('.').abspath+'/gen-cpp/'

print py_dir
py_dir_c = env.Command(py_dir, [],
                   [Mkdir(py_dir)])

cpp_dir_c = env.Command(cpp_dir, [],
                   [Mkdir(cpp_dir)])

proto_files = env.Protoc(
    [],
    proto,
    PROTOCPYTHONOUTDIR=py_dir, # set to None to not generate python
    #PROTOCPYTHONOUTDIR=None, # set to None to not generate python
    #PROTOCCPPOUTFLAGS = cpp_dir, #Dir('.').abspath+'/gen-cpp/',
    PROTOCOUTDIR = cpp_dir # defaults to same directory as .proto
)
#for f in proto_files:
#  Return(f)
Return('proto_files')

