Import('env build_config')

sources = [ "MRFLP.cpp", "TagLP.cpp", "DepParseLP.cpp"]

if build_config['has_sri']:
  sources += ["LPBuilder.cpp"]
  
trans_lib = env.Library('lp', sources )

Return('trans_lib')

