Import('env')

proto = ["hypergraph.proto", 'lexical.proto', 'tag.proto', 'dep.proto',
         'features.proto', 'translation.proto']

py_dir = Dir('.').abspath+'/../../python/relaxdecode/interfaces/'
cpp_dir = env["HYP_PROTO"][2:]


py_dir_c = env.Command(py_dir, [],
                   [Mkdir(py_dir)])

cpp_dir_c = env.Command(cpp_dir, [],
                   [Mkdir(cpp_dir)])


proto_files = env.Protoc(
    [],
    proto,
    #PROTOCPYTHONOUTDIR=None,
    PROTOCPYTHONOUTDIR=py_dir, # set to None to not generate python
    PROTOCOUTDIR = cpp_dir, #Dir('.').abspath+'/gen-cpp/',
    #PROTOCOUTDIR = cpp_dir # defaults to same directory as .proto
)

Return('proto_files')


