Import('env')

proto = ["graph.proto", 'mrf.proto']

py_dir = Dir('.').abspath+'/../../python/relaxdecode/interfaces/'
cpp_dir = env["GRAPH_PROTO"][2:]

Mkdir(py_dir)
Mkdir(cpp_dir)

proto_files = env.Protoc(
    [],
    proto,
    PROTOCPYTHONOUTDIR=py_dir, # set to None to not generate python
    PROTOCOUTDIR = cpp_dir # defaults to same directory as .proto
)

Return('proto_files')
